### ISSUE TITLE
[RFC] 重新明确 Plugin 及 Framework 配置项的合并逻辑

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#109]
问题描述：

- 目前的 `Plugin` / `Framework` 配置项中，`path` / `package` 不应当同时存在（优先级 / fallback 令人头大且意义不大）
- 现行实现中，除 `Framework` 自身单独设计递归结构时，可以确保单个配置项不合并，其他 Plugin 会在 `ConfigurationHandler` 中按照统一逻辑处理深合并，由此可能造成单个插件合并结果中 `path` / `package` 同时存在
  - 深合并有两种场景会被触发：
    - 跨环境配置，如同时存在 `plugin.dev.ts` 和 `plugin.default.ts`
    - 用户项目和依赖的 `Framework` 或 `Framework` 依赖链各项间，同时存在 `plugin.${env}.ts`
- 深合并逻辑不应被直接替换为覆盖逻辑，存在下级同时配置了 `enable` 和 `package`，上级需要单独修改 `enable`，package 配置项需被继承

待选解决方案：

1. 撤销 `package` 字段，统一采用 `path`，要求用户使用 `path: getPath('packageName')` 指定插件
2. 利用 `deepmerge` 中的 `custommerge` 方法，对含有 `enable` / `path` / `package` 的配置项单独处理 cc @JerrysShan （`ConfigurationHandler` 需限定这一行为在 `plugin` 作用域）
3. 在合并链中增加隐式规定：
  - 如果已有配置不包括 `path` 或 `package`，则允许待合并项合入
  - 如果已有配置包括 `path` 或 `package`，待合并项中不包括这两字段，则允许待合并项合入
  - 如果已有配置包括 `path` 或 `package`，待合并项中包括这两字段，则不允许待合并项合入，显式抛错
  - 合并链目前不完全是线性的，存在内/外层和环境两集，需保证优先级为 外层指定环境 > 外层default > 内层指定环境 > 内层 default
 
Co-Author-by: @wengeezhang

**Comment by hyj1991** [comment]
深合并后单个插件不可能会同时具有 `path` 和 `package` 属性

**Comment by noahziheng** [comment]
> 深合并后单个插件不可能会同时具有 `path` 和 `package` 属性

设计上应当如此，但是目前的实际逻辑是会的，如:
```ts
// plugin.dev.ts
export default {
  test: {
     enable: true,
     path: '../'
  }
};

// plugin.default.ts
export default {
  test: {
     enable: true,
     package: '@artus/test'
  }
};

// 合并结果
{
  test: {
     enable: true,
     package: '@artus/test',
     path: '../'
  }
}
```

framework 场景下因为合并逻辑一致，问题相同

**Comment by hyj1991** [comment]
这不是设计的问题。。。

dev 覆盖 default 是配置覆盖规则，本来就是 env 覆盖默认，出现这种情况是如果 dev 配置的 path 不对，不能写相对路径，path 必须是绝对路径（或者框架处理为绝对路径）

**Comment by hyj1991** [comment]
如果有用户配置 config.dev.ts 同名插件 path 路径，本来就是需要扫描这个 path 路径对应的插件目录，而不能去扫描 default 中的同名配置，这个设计是没有问题的。

**Comment by noahziheng** [comment]
飞书会议结论：
- 问题确认存在，本质上是配置合并逻辑针对 pluginConfig 缺乏特殊处理
- 方案 3 规则可行，改动可以明确在 Scanner.getAllConfig 方法内完成
- 避免运行时出现有歧义的合并结果，考虑将 pluginConfig 项从运行时移除（现在确实也没用）
