### ISSUE TITLE
[RFC]: 开放自定义 Trigger 的能力

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/core#112]
在实现上层框架的时候如果通过继承 artus 内部 Trigger， 然后通过覆盖的方式注册自定义的Trigger ，如果扩展了自定义方法  ，开发时类型没办法提示； 所以决定抽象一个 TriggerType ，自定义 Trigger 实现这个 TriggerType ，然后Application 中override get trigger 的类型 ，达到类型覆盖的方式。具体实现件 #94

**Comment by noahziheng** [comment]
cc @hyj1991 @DuanPengfei

**Comment by noahziheng** [comment]
已经在 #94 #188 完成，相关的覆盖问题仍在讨论：related #201
