### ISSUE TITLE
[RFC] startPipeline 缺少对 ctx.container 操作的时机

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#113]
```ts
async initContext(input: Input): Promise<Context> {
  const ctx = new Context(input, new Output());
  ctx.container = new ExecutionContainer(ctx, this.app.getContainer())
  return ctx;
}

async startPipeline(input: Input = new Input()): Promise<Context> {
  const ctx = await this.initContext(input);
  await this.pipeline.run(ctx);
  return ctx;
}
```

以上是目前的 `startPipeline` 的实现。

这个过程其实把初始化 `Context` 以及执行流水线耦合到一起，这会导致无法在执行流水线之前往 `Conext` 提供的 `ExecutionContainer` 中设置 `EXECUTION` 实体（或者类）。

一种改动办法是：

```ts
async initContext(input: Input = new Input()): Promise<Context> {
  const ctx = new Context(input, new Output());
  ctx.container = new ExecutionContainer(ctx, this.app.getContainer())
  return ctx;
}

async startPipeline(ctx: Context): Promise<Context> {
  await this.pipeline.run(ctx);
  return ctx;
}
```

将流水线执行和 Context 初始化解耦，当然也可以使用 `??=` 兼容以前的无参数流水线逻辑：

```ts
async startPipeline(ctx: Context): Promise<Context> {
  ctx ??= await this.initContext();
  await this.pipeline.run(ctx);
  return ctx;
}
```

**Comment by hyj1991** [comment]
cc @noahziheng

**Comment by noahziheng** [comment]
个人观点：
1. 其实原则上不应当往 `ctx.contianer` 再显式 set **类(type)**，对于这些用户/插件开发者定义的 Scope 为 Execution 的 Class，应当统一被 `app.contianer` 托管，在 `new ExecutionContainer` 时被“继承”（即现有 Loader 的做法）
2. 真正需要被放进去的其实是部分请求相关的“量(value)”，如 HTTP 的 Headers，但这些值目前被 Input/Output 以 Map 的形式托管，这个部分的设计是否合理其实有必要重新审视（即加强 ExecutionContainer 的作用范围）
3. 允许外部初始化 Context 确实可以解决很多争议，但相当于把实现自由度完全交给了协议实现的设计者，可能会有魔法出现

**Comment by noahziheng** [comment]
cc @DuanPengfei @Beace @wengeezhang

**Comment by hyj1991** [comment]
类确实不需要，但是 EXECUTION 对应的实例变量，如果放置在 `input` / `output` 中实现共享，带来的问题是还是会给用户暴露 ctx 的概念，如果可以显式在上层框架 set 进 execution container，那么可以更自然使用 Inject ID 的形式注入：

```ts
@Inject('REQUEST')
private req;
```

类似这样

**Comment by hyj1991** [comment]
> 真正需要被放进去的其实是部分请求相关的“量(value)”，如 HTTP 的 Headers，但这些值目前被 Input/Output 以 Map 的形式托管，这个部分的设计是否合理其实有必要重新审视（即加强 ExecutionContainer 的作用范围）

最后针对这个我谈下我的想法吧，放置在 input / output 中实现共享另一个副作用是用户可以通过 ctx 来获取这些本应该 `Inject` 的实体，而实际上我们不应该让用户有这样一种绕过 IoC 的方式，就应该限制所有需要的属性通过 Inject 的形式来获取。

相比限制上层框架的黑魔法，我更加担心用户自由使用 ctx 带来的黑魔法副作用，毕竟前者是可控的或者符合预期的，后者则是完全不可控的。

**Comment by noahziheng** [comment]
@hyj1991 实际上我想表达的想法比你还要更激进一些
1. 类似 `@Inject('REQUEST')` 中放置的实质还是 `量(value)`，而非 `类(type)`，实例化动作不是容器完成的
2. 我的想法是如果想要完全应用 ExecutionContainer 的威力，有没有可能直接抛弃 Input 和 Output，所有 Key 平铺在容器中，对于用户操作只有 Container 一条通道，即 ctx ===（等效） container
3. 在我们的上层框架实现中，Artus Pipeline 的 Context 是对用户完全屏蔽的，只能通过 contianer 操作

**Comment by DuanPengfei** [comment]
@noahziheng 感觉补充一下现在 GuluX 的代码可能比较好理解一些，比如咱们现在激进的做法，全部地方都是 inject 这种。

**Comment by noahziheng** [comment]
Show some code.
PS: 求生欲！以下代码仅用于表述我在上面 Issue Reply 中的思路，不涉及字节框架 GuluX 的现行代码（实质上现行代码设计多处 Wrap 和 as，也不好理解）

对于用户侧，在使用上下文信息时，均应通过 Inject 属性或显式的参数装饰器（语法糖，如下的 Body/Query，本质上包装了对 Contiainer 的操作）实现：
```ts
export default class BookController {
  constructor() {}

  @Inject(HttpInjectEnum.RawRequest)
  req: IncomingMessage;

  @Inject(HttpInjectEnum.RawResponse)
  res: ServerResponse;

  @Inject(HttpInjectEnum.Host)
  host: string;

  @Inject()
 logger: GuluXLogger

  /**
   * /root/book/booklist 
   * '/root' is the property globalPathPrefix value in ../config/config.default.ts
   * @returns 
   */
  @Get('/booklist')
  async getBookList(@Query() query: BookQuery, @Body() body: BookBody) {
    this.logger.info('getBookList', query, body);
    this.logger.info('Request headers:', this.req.headers);
    this.logger.info('Request host:', this.host);

    this.res.setHeader('x-gulux-test', 'hahaha');

    return {
      bookList: [] // From external
    };
  }
}
```

对应的，Trigger 的处理可以改造成（伪代码，省略 use）：
```ts
@DefineTrigger()
export default class HttpTrigger {
  async respond(ctx: Context) {
    try {
      const res = ctx.container.get(HttpInjectEnum.RawResponse);
      const body = ctx.container.get(HttpInjectEnum.ResponseBody);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(body));
    } catch (err) {
      console.log('HttpTrigger respond catch err', err);
    }
  }
  async initContext(initParams: Map<string, unknown>): Promise<Context> {
    const ctx = new Context();
    ctx.container = new ExecutionContainer(ctx, this.app.getContainer());
    ctx.container.set({ type: ExecutionContainer, value: ctx.container });
    for (const [paramKey, paramValue] of initParams.entries()) {
      ctx.container.set({
        id: paramKey, 
        value: paramValue
      });
    }
    return ctx;
  }
  async startPipeline(initParams: Map<string, unknown>): Promise<Context> {
    const ctx = initContext(initParams)
    await this.pipeline.run(ctx);
    return ctx;
  }
}
```
上述 Trigger 可以进一步简化，把 contianer.set 动作移到到外面，接受 executionContainer 作为参数
PS：此处引出，如果去掉 Input/Output，那 Context 仅用于持有 ExecutionContainer，是不是也多余了

综上，我认为现在的 Input/Output/Context/ExecutionContainer 中的混乱关系，可以被统一的 ExecutionContainer 所替代

**Comment by hyj1991** [comment]
我觉得有一点应该达成共识：Execution container  本身也不应该直接暴露给用户。

用户使用的动作应该局限于需要的属性则 `@Inject(xxx)` 来使用，没有多余的能力。

但是对于上层框架开发者，则不需要这个限制。

**Comment by noahziheng** [comment]
> 我觉得有一点应该达成共识：Execution container 本身也不应该直接暴露给用户。
> 
> 用户使用的动作应该局限于需要的属性则 `@Inject(xxx)` 来使用，没有多余的能力。
> 
> 但是对于上层框架开发者，则不需要这个限制。

这一点现在已经是共识吧，目前讨论的 Input/Output/Context/ExecutionContainer 这些元素都不应被直接暴露给用户

**Comment by hyj1991** [comment]
取消掉 Context 用 execution container 替代，那么就需要给用户直接访问 contanier，这样在我看来和 context 没啥区别。

无非是以前的 ctx.xxx 变成了 container.set / get

**Comment by noahziheng** [comment]
> 取消掉 Context 用 execution container 替代，那么就需要给用户直接访问 contanier，这样在我看来和 context 没啥区别。
> 
> 无非是以前的 ctx.xxx 变成了 container.set / get

不是哇，为什么一定要 container.set / get，姿势难道不应该是 Injectable + Inject？

**Comment by hyj1991** [comment]
针对的是实体，不是类，比如用户想要在中间件 A 存入一个变量 a，然后在自己的下一个中间件 B 使用。

`Injectable / Inject` 是编译时的而非运行时调用的

**Comment by noahziheng** [comment]
@hyj1991 我不清楚这是否是包袱造成的理解差异

或许 middleware 中有限度的使用 set，用户使用 Inject 使用，其实是合理的

对于通常的 controller => service 的调用过程中，应当使用显式的参数传递而非 ctx / 借助 container

**Comment by hyj1991** [comment]
用户也可以写 middleware 的，这样不是还是把 container.set 暴露给用户了么

**Comment by noahziheng** [comment]
@hyj1991 @DuanPengfei 我认为需要一次语音的会议对争议予以确认

@JerrysShan  再看下还有没其他的意见呢

**Comment by hyj1991** [comment]
> 对于通常的 controller => service 的调用过程中，应当使用显式的参数传递而非 ctx / 借助 container

并不是 `ctrl -> serv` 的问题，这里传参是没问题的，ctx 作用是流水线处理用户注入的上下游流水线函数之间的数据共享。

**Comment by hyj1991** [comment]
不过有一点我认为是可以的：

```ts
const res = ctx.container.get(HttpInjectEnum.RawResponse);
const body = ctx.container.get(HttpInjectEnum.ResponseBody);
```

流水线的结果使用 container 存储，但是要看下会不会引发其他问题。

**Comment by hyj1991** [comment]
接上面，这个实际上现在也是可以实现的，目前的 ctx.output 的使用是上层控制的，按照我最开始写的这个改动，`initContext` 后可以拿到 ctx.container 预设这些输入输出类的对象放到到 execution container 中

**Comment by JerrysShan** [comment]
我们在实践中，把能够托管给容器处理的，尽可能的托管；在 pipeline 中的 ctx 对象只保留了 artus core 中的核心属性 input , output
```typescript
calss Context implements BaseContext{
 input: { req: Reqeust, resp: Response};
 output: {data: any}
}
```
> 在中间件上下游流水线函数之间的数据共享，

如果是类似 Koa 中在 a 中间件设置值 `ctx.xx = 'hello world'` ， 然后在 b 中间件获取 `ctx.xx` 值这样的操作的话，感觉我们应该尽量避免

**Comment by noahziheng** [comment]
语音会议初步结论：
- 认可原始 RFC 中的 API 改动，调整 ctx: Context 为 startPipeline 的参数
- Input/Output 暂时不主动去掉，通过 API 改动允许继承方 miss 掉
- output.data 可以考虑在 respond 被替换为 container 实现
