### ISSUE TITLE
[BUG] 多环境 Config 合并不正确(v1.0.0-alpha.16)

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#154]
### 现象

运行时 env 设定失效

### 成因

#131 调整配置合并逻辑为运行时 Object.assign 所有配置文件，这一行为基于 Manifest 中应只包括自身环境的配置文件，`Scanner` 中对此估计不足，现时实现不具备这一效果，导致运行时将全部 Config 合并，造成配置项混乱

**Comment by hyj1991** [comment]
启动期其实没有 env 的概念了，因为 Scanner 扫出来所有 env 下的 manifest，交给启动期的是确定 env 下对应的 manifest，所以这里的合并并没有问题，当时我有个 comment
