### ISSUE TITLE
[RFC] 针对 Module Loader 处理的类调整默认 Scope

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#156]
### 背景

在当前的实现中，所有最近加载到容器中的类，默认的 Scope 均为 `SINGLETON`，而对于业务场景中最常使用的 Controller/Service 等元素，作用域通常都需要是 `EXECUTION`；

由于 Controller 通常会被定义单独的装饰器用于路由元数据定义，也会在其中定义 Scope 为 Execution，但 Service 或类似地位的 Domain 类，就会需要通过下述代码编写：

```typescript
import { Injectable, ScopeEnum } from '@artus/core';

@Injectable({
  scope: ScopeEnum.EXECUTION
})
export default class HelloService {}
```

这无疑是非常冗余的，期待应该是可以通过 `@Injectable()` 直接完成 Service 的声明

### 方案

- injection 中修改 set type 行为默认值
  - 影响面较大，分支链路颇多（factory/handler/value）
- 上层框架覆写 Injectable 装饰器，或提供 Service 装饰器
  - 不大优雅，且与不限定 Service 以便实施 DDD 等领域实践的思路相悖
- 通过在 module loader 的 set 过程中，增加默认的 scope，如需覆盖，仍可通过 `@Injectable()` 的参数实现
  - BREAKING CHANGE，初步认为可行

/cc @hyj1991 @JerrysShan

**Comment by wengeezhang** [comment]
方案3，怎么识别出 是service （Service 或类似地位的 Domain 类）

**Comment by noahziheng** [comment]
@wengeezhang 其实不用识别，能被 module loader 处理的不是 Controller 就是 Service，其他的特殊类（需要单例）的不会被这个 loader 处理

**Comment by wengeezhang** [comment]
默认增加scope，有点黑盒。方案2  lgtm  (且与不限定 Service 以便实施 DDD 等领域实践的思路相悖 没get 到点)

**Comment by JerrysShan** [comment]
结论：采用方案三 ，module loader 增加默认的 scope
