### ISSUE TITLE
[RFC]: Injection 跨作用域注入的问题

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/core#178]
现在 Injection 里面有三种 scope：Singleton，Transient， Execution。有种情况是在一个单例的作用域内注入了一个请求作用域的实例，目前是允许这种行为的；但是这种行为存在一定的隐患，如果请求作用域有依赖请求周期中的数据，会出现异常。

我们针对这种跨作用域使用的情况，我们要不要抛出异常，来提醒用户，并且考虑增加选项允许这种行为

**Comment by hyj1991** [comment]
这个我觉得和 Container 覆盖一样，默认抛错，可选参数强制忽略即可

**Comment by hyj1991** [comment]
这里确实需要处理下，对于第一次接触 IoC 的开发者，很容易犯的错误，如果不提示可能会造成运行时未定义行为

**Comment by whxaxes** [comment]
感觉抛异常好一些

**Comment by JerrysShan** [comment]
![image](https://user-images.githubusercontent.com/13977368/187589368-0ab25da2-73f7-4261-92de-05ff370f8ae3.png)
校验规则梳理了下，主要针对上面表格中打问号的地方进行校验，看下有没有其他问题 cc @DuanPengfei @noahziheng @hyj1991 @whxaxes

**Comment by hyj1991** [comment]
@JerrysShan Transient 应该可以在任意 Scope 注入，因为是每次实例化

**Comment by JerrysShan** [comment]
如果在请求生命周期外实例化一个 Transient scope 的对象，如果引用了 req 这些属性，也会有问题吧

**Comment by hyj1991** [comment]
没太看懂，Transient 不应该在 execution container 里实例化吧？它可以放到 global container 里面，反正是每次实例化

**Comment by JerrysShan** [comment]
> 没太看懂，Transient 不应该在 execution container 里实例化吧？它可以放到 global container 里面，反正是每次实例化

比如在 `app.container` 里面放了一个 Transient `class A `，然后里面注入了一个 Execution `class B`
```typescript
@Injectable({scope:ScopeEnum.Transient})
class A {
@Inject()
b:B
}

@Injectable({scope:ScopeEnum.Execution})
class B {
  req: Request;
 
}
app.container.set({type:A});
app.container.set({type:B});
const a=app.container.get(A); // 因为 b 使用了 request ，会出现异常

```

**Comment by hyj1991** [comment]
这个例子和你描述的是反过来的，是在 transient scope 里实例化 execution，我的意思是反过来，任意 scope 都可以 inject transient

**Comment by hyj1991** [comment]
等于那个图最后一列应该都是 √

**Comment by JerrysShan** [comment]
> 这个例子和你描述的是反过来的，是在 transient scope 里实例化 execution，我的意思是反过来，任意 scope 都可以 inject transient

把上面的表格描述了下 ，我意思在 transient scope 的 class 里面注入了 execution scope 的 property

**Comment by hyj1991** [comment]
@JerrysShan execution class 里面 inject transient 应该是没问题的吧？

**Comment by JerrysShan** [comment]
> @JerrysShan execution class 里面 inject transient 应该是没问题的吧？

对，这种应该可以，之前考虑不全面 cc @noahziheng @DuanPengfei

**Comment by hyj1991** [comment]
|  | Singleton  |   Execution |  Transient|   
| :----- | :-----| :----- | :----- | 
|  Singleton | ✅  |  ✅   |  ✅  |
|  Execution |  ？  |   ✅  |     ？ |
|  Transient |  ✅   |  ✅  |  ✅ |

**首列是 class scope ，首行是 property scope**

我感觉应该是这样 @JerrysShan

**Comment by JerrysShan** [comment]
经过沟通，结论如下：
1. 只针对 Singleton 引用 Execution 的场景进行校验抛错，增加选项允许跳过检查
2. 至于 Transient 引用 Execution 的场景，需要根据使用情况决定，sdk 里面不做校验，交给用户决定

|  | Singleton  |   Execution |  Transient|   
| :----- | :-----| :----- | :----- | 
|  Singleton | ✅  |  ❌    |  ✅  |
|  Execution |  ✅  |   ✅  |     ✅ |
|  Transient |  ✅   |  ❓    |  ✅ |

**首列是 class scope ，首行是 property scope**

cc @hyj1991 @noahziheng @DuanPengfei @whxaxes
