### ISSUE TITLE
[RFC] Scan 阶段 Framework 的优先级问题

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#187]
# 背景

在 Scanner 的 [这段代码](https://github.com/artusjs/core/blob/master/src/scanner/scan.ts#L105) 中，指定的优先级为：
ScannerOptions 中的 framework 字段（下称参数字段） **>**  用户目录下的配置文件（通常位于 config/framework.ts，下称配置文件）

# 问题

在通常的使用场景中，参数字段的作用是用于上层框架在其工具链/包装层中指定默认的 Framework，按照现有设计，一旦参数字段存在，用户配置即失效，不符合场景诉求

# 解决方案

颠倒 scan.ts#L105 中的默认顺序：
- getAllConfig 取得的用户配置中存在 framework 配置文件时，优先消费
- 否则使用 ScannerOptions 的 framework 字段作为兜底
- 全没有时忽略 Framework 逻辑，继续 Plugin 维度的 walk

@hyj1991 @whxaxes @JerrysShan

**Comment by JerrysShan** [comment]
感觉以用户配置中的优先级更高比较好

**Comment by hyj1991** [comment]
这个是特别设计的，否则用户可以任意指定，工具链无法控制用户行为

**Comment by whxaxes** [comment]
我们内部大部分场景都不会让用户配置 framework.ts ，但是有部分定制业务会有他们自己的 framework 需要指定，包括 egg 也是允许用户在 pkg.egg.framework 来指定的，这种也算是用户配置，所以`用户配置 > Scanner 配置`可能确实会合理一些，不然业务方有定制需求也不好处理了？

**Comment by atian25** [comment]
+1 如 吖猩，在社区场景下可以给用户指定。
我们内部禁止使用自定义框架的场景，在内部解决

**Comment by hyj1991** [comment]
这个点我是从管控的角度出发设计的，看大家意见吧，如果大部分人投票应该让用户的优先级 > 工具链的优先级，那可以修改

**Comment by noahziheng** [comment]
个人认为，现在既然存在 config/framework 这种形式的用户配置，那么上层通过覆盖让它失效的逻辑肯定是不合理；如果上层有自己的强管控诉求，可以在工具链通过文件检查不让这组文件存在

**Comment by atian25** [comment]
> 这个点我是从管控的角度出发设计的，看大家意见吧，如果大部分人投票应该让用户的优先级 > 工具链的优先级，那可以修改这里的逻辑

可以在 scaner 这里默认支持用户配置，但最好抽一个函数出来，我们在内部场景下，可以继承 Scanner 覆盖掉这段逻辑。

**Comment by hyj1991** [comment]
其实从社区角度，社区用户可以不用这个工具链的配置，自由发挥，工具链的设计本身就应该带有管控属性

**Comment by hyj1991** [comment]
或者只用工具链，但是不指定任何强制配置，这种也可以给用户自由发挥；在工具链中增加指定配置，本质上是替用户做决定，不想被限制的用户可以不用指定具体配置的工具，而不是限制用户可以覆盖工具链的指定配置

这是我的看法。

**Comment by noahziheng** [comment]
@hyj1991 此处你混淆了“终端用户”和“上层框架用户”；
如果自己是上层框架的视角，工具链自身强控制，可以让终端用户不知道自己其实可以配置 framework 即可实现“管控”；
但作为 Core 本身，要求上层框架要么管控别配，要么都开放给用户不许有默认值，这是很武断的。

cc @DuanPengfei @JerrysShan : 作为这个 case 本身，我们也再看下我们要的管控是什么样的，是否有必要限制用户使用 `config/framework`

**Comment by hyj1991** [comment]
工具链是面向终端用户的，我们现在的设计下并不存在面向非终端用户而仅是框架继承链中某个环节的工具链，这里的配置也是如此。

**Comment by hyj1991** [comment]
所以我并不认为这种管控限制了社区用户，譬如提供一个 `artus-scripts`，按照目前的设计我们可以给个 `--framework=xxxx` 的 optional 配置，如果不希望用户受限，可以不配就行了，完全按照用户指定的配置

**Comment by noahziheng** [comment]
@hyj1991 有没有一种可能，我现在的出发点就是我是工具链（doge
对于工具链视角（不考虑你们这么强的管控策略），遵守 Artus 规范的话，我应当使用 `config/framework` 允许用户指定框架，但在用户没指定的时候，我需要一个默认值保证大多数场景下都用的插件被引入。

**Comment by JerrysShan** [comment]
> 所以我并不认为这种管控限制了社区用户，譬如提供一个 `artus-scripts` 作为官方的工具链，按照目前的设计我们可以给个 `--framework=xxxx` 的 optional 配置作为可选的管控手段；
> 
> 如果不希望用户受限，不进行这个可选项的就行了，即可完全按照用户指定的配置来自由发挥。
但是作为工具链，里面的配置优先级也不应该高于用户配置的优先级

**Comment by hyj1991** [comment]
我这样设计并非是从我们自己应用的管控角度出发（参加天猪和吖猩的回复）

而是基于：artus 并不是脱离工具链无法启动，它有明确的扫描入口和启动入口的设计，在这个基础上，还需要使用工具链来完成加载启动应用的动作，必然携带了一些目的性，如果设计本身有工具链和没有工具链并不存在差别，那么提供统一工具链的意义也就没了。

或者换个角度，统一的工具链可能只需要负责更加通用的进程守护之类的职责，而无需约束特定启动配置项（因为都可以在应用层指定）

**Comment by hyj1991** [comment]
当然就本 RFC 而言，我并不反对在 Scanner 中修改覆盖顺序，以实现更加自由的自定义工具链设计（如果大多数参与者认为内置的限制是没有必要的话）
