### ISSUE TITLE
[RFC] 涉及需全局唯一的实体如何统一“覆盖”机制

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#201]
在之前 #190 #165 https://github.com/artusjs/spec/issues/28 的讨论中，反复出现一些 Artus Core 内部的单一实体（Core 只需有一个实现，与 Loader 不同）需要有被自定义的需求，如：

- Trigger
  - 最主要需要被协议/上层框架自定义的类
  - 在 Artus 内部暂无调用点，https://github.com/artusjs/spec/issues/28 中的 ExceptionFilter 可能引入
- Logger
  - Artus 内外均需要使用
  - 上层框架通常需要覆盖对应实现
- ExceptionFilter（讨论中）
  - Artus 内部无需实现
  - 上层框架/用户工程通常按需实现，全局唯一
- 其他属性接近的类（Scanner、Plugin）
  - 因各种原因暂未开放自定义
  - 后续开放效果接近

在早期的实现中，我们的机制是：

- 统一 Enum 常量作为 `id`
- 统一 DefineXXX 装饰器封装逻辑
- Loader 或上层框架中的定制逻辑向 Container 中覆盖
- 要求使用 InjectEnum 取值
- Contianer 中有特殊处理，使用 id 覆盖的，也可通过类 Inject（双 set 机制 https://github.com/artusjs/injection/pull/14）

上述的 Issue 讨论后，我们通过 #188 #193 两个 PR，移除了这一机制，但之后各上层框架的认知并不十分统一，分为两类：

- 彻底抛弃覆盖，各场景下均为独立的类
  - 但实际实现中，这一思路较为局限，如 Logger 在 Artus 中使用，只能拿到内部的 Logger，不能通过上层框架覆盖的类打印日志
- 使用导出的类替代，Injectable 中显式传入类作为 `id`，取值亦可用类直接 Inject
  - 如 `@Injectable({ scope: ScopeEnum.SINGLETON, id: Trigger })`

综上，我们有必要对“覆盖”这一机制进行明确：

1. 到底什么需要覆盖（如 Trigger 的特殊性 ）
2. 到底用什么形式覆盖，能否统一

@DuanPengfei @hyj1991 @JerrysShan @Beace  @atian25  @whxaxes

**Comment by noahziheng** [comment]
一种新思路：

其实覆盖问题有一些共识：类优于枚举、显式优于隐式。
既然全局唯一的其实是类实体，可以通过我们已有的 config 机制来将整个过程进一步显式化，以 Logger 为例：

实现：

```ts
// src/my_logger.ts
import { Injectable, LoggerType } from '@artus/core';

@Injectable()
export class MyLogger implements LoggerType {
  // ... implemention
}
```

配置：

```ts
// src/config/config.default.ts
import { ApplicationConfig } from '@artus/core';
import { MyLogger } from '../my_logger';

export default {
  logger: MyLogger
} as ApplicationConfig;
```

外部可照常使用： 
```ts
@Inject() 
logger: MyLogger;
```

Artus 内部使用 `app.container.get(app.config.logger);` 替代

**Comment by hyj1991** [comment]
覆盖我理解的主要收益在两种场景下：
* 希望下游框架 / 插件的内置逻辑可以被上层应用以成本比较低的形式进行重新实现
* 一份基础类型（interface）对应多份具体实现，希望应用不更改代码仅切换（工具链指定）插件 / 框架

**Comment by hyj1991** [comment]
通过配置来处理，有这样的问题

```ts
// 上层框架
export default {
  logger: FrameworkerLogger
}

// 应用
export default {
  logger: ApplicationLogger
}
```

`FrameworkLogger` 和 `ApplicationLogger` 可以实现一样的 interface，但是用户要切换时，势必要更改应用代码，因为 Inject 的类型会变

**Comment by hyj1991** [comment]
类 id 覆盖的劣势是所见不所得，反直觉，但是优势是类型定义可以靠 `design:type` 反射无需用户指定，也不需要从上层框架或者 core 中引入两遍重复的逻辑：
```ts
import { REQUEST } from ’core/constant‘;
import { Request } from 'core/type'

@Injectable()
export default class Foo {
  @Inject(REQUEST)
   private req: Request;
}
```

类似这样的重复形式


其实常量覆盖这种形式需要用户手动指定类型，可以认为是另一种意义上的反直觉，毕竟手动指定就意味着可以任意指定

**Comment by hyj1991** [comment]
或者说设计上只要把基类设计成抽象类，即只提供方法，不提供实现，作为实体 interface：

```ts
@Injectable()
export default class Logger {
  info() { throw new Error('not implement!'); }
  warn() { throw new Error('not implement!');  }
}
```

这个角度，这样的抽象实体类作为 IoC 容器 id 似乎也比较合理（如果运行时不会擦除类型，interface 能作 id 和反射就比较完美）。
