### ISSUE TITLE
framework和plugin配置里关于 path 信息处理的问题

### ISSUE THREAD

**Issue by DevXiaolan** [artusjs/core#228]
现在framework和plugin 的配置里都有 path 或者 package 信息，
对于 package 的场合问题不大，因为有用到 require.resolve 。

而 path 的场合，是直接处理成相对/绝对路径，这里其实有点问题

比如我一个 framework 或 plugin 是不打算发布到 registry 的，那我肯定长期使用 path 的配置去引用，
那我建议需要参考这个包的 package .json 的 main 属性，而不是指定到具体的 dist 、 build 、libs 这样的目录位置。

**Comment by noahziheng** [comment]
看起来是可行的，require.resolve 之前先判断一下有 package.json 的目标就解析 main 字段

**Comment by noahziheng** [comment]
我这边可以改改，顺便重构一下 PluginConfigLoader，看起来对内部应该是没有副作用
cc @atian25 @DuanPengfei @whxaxes

**Comment by DevXiaolan** [comment]
你动手我就不动了，在代码的整体性方面肯定没有你处理得好。

**Comment by atian25** [comment]
解析 main 够不？ export 那一堆配置呢？有没有现成的库来分析这块的？

**Comment by DevXiaolan** [comment]
> 解析 main 够不？ export 那一堆配置呢？有没有现成的库来分析这块的？

就是体力活，我溜了 🤣

**Comment by JerrysShan** [comment]
> 看起来是可行的，require.resolve 之前先判断一下有 package.json 的目标就解析 main 字段

main 字段不是默认会被 require 解析吗？

**Comment by DevXiaolan** [comment]
> > 看起来是可行的，require.resolve 之前先判断一下有 package.json 的目标就解析 main 字段
> 
> main 字段不是默认会被 require 解析吗？

说的是，如果配置里是使用 path 来提供路径，就不会走 require 的处理，这块要自己解析 main

**Comment by noahziheng** [comment]
@atian25 或者就是说这里的解析 main 也走 require.resolve 拿到之后取对应那一层目录，这样就能做到兼用 main/exports

**Comment by noahziheng** [comment]
@JerrysShan 现在的 path 加载没过 require.resolve

**Comment by atian25** [comment]
> @atian25 或者就是说这里的解析 main 也走 require.resolve 拿到之后取对应那一层目录，这样就能做到兼用 main/exports

嗯，resolve 后再 relative？
