### ISSUE TITLE
RFC:  plugin 中meta文件的内容

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/core#25]
```typescript

export default {
    name: 'plugin1',
    dependencies: [
        {
            name: 'plugin2',
            enable: true,
            package: '@artus/plugin2'
        },
        {
            name: 'plugin3',
            enable: true,
            path: path.resolve(__dirname, 'plugin3')
        }
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            enable: true,
            package: '@artus/plugin4'
        },
        {
            name: 'plugin5',
            enable: true,
            path: path.resolve(__dirname, 'plugin5')
        }
    ]
}

```
根据昨天晚上的讨论结果，plugin 配置文件的内容如上，大家看下有什么问题不
@noahziheng @hyj1991 @DuanPengfei @Beace

**Comment by hyj1991** [comment]
`config/plugin.ts` 中不是应该定义依赖的插件列表么？

这个是某个具体插件的元信息吧

**Comment by JerrysShan** [comment]
昨天会议的结论元信息不是说先暂定在plguin中，我理解的有偏差， @DuanPengfei @noahziheng 也确认下

**Comment by hyj1991** [comment]
暂定在 plugin 中指的是插件中的某个文件存放元信息吧？比如插件根目录的 `plugin.json` 之类的

config/plugin.ts 本身也不应该在插件中存在，这个配置项是给 application 和 framework 组织插件使用的

**Comment by DuanPengfei** [comment]
@hyj1991 这个看起来就是插件的元信息加上依赖信息吧，昨天聊的是把插件元信息和依赖信息都声明在 plugin.ts 中吧，这里带着 enable 的应该在 Application / Framework 里的写法，如果是在一个插件内，路径也不会是 config/plugin.ts 了吧，而是跟 package.json 同级的一个 plugin.ts 这种。内容上还是描述元信息和依赖关系，用于扫描。

**Comment by DuanPengfei** [comment]
plugin 包中
- package.json // npm 包的描述
- config // 插件配置格式声明及默认值描述
- xxx.ts // 插件代码等其他内容的文件
- plugin.ts // 插件的元信息、依赖关系的描述
```typescript
export default {
    name: 'xxx',
    dependencies: [{ name: 'yyy' }],
    optionDependencies: [{ name: 'zzz' }]
}
```

application / framework 中
- xxx.ts 代码
- ${config 路径}/plugin.ts // 描述依赖的插件信息
```typescript
export default {
    dependencies: [{ name: 'xxx', enable: true }]
}
```

@hyj1991 @JerrysShan 我是这样理解的，在插件内的自身元信息的声明文件，和在 application / framework 中的依赖声明，是有一定区分差异度的。

**Comment by DuanPengfei** [comment]
> 暂定在 plugin 中指的是插件中的某个文件存放元信息吧？比如插件根目录的 `plugin.json` 之类的
> 
> config/plugin.ts 本身也不应该在插件中存在，这个配置项是给 application 和 framework 组织插件使用的

是这个意思，我上面给了一个示例，在 application / framework 里才会在 ${config 路径} 存在一个 plugin.ts 用于描述需要的插件及是否开始插件。如果是在 plugin 内这个 plugin.ts 是插件元信息及依赖的声明，不会包含 enable，路径上也会直接在顶级，不放入 config 中去。

**Comment by hyj1991** [comment]
> 是这个意思，我上面给了一个示例，在 application / framework 里才会在 ${config 路径} 存在一个 plugin.ts 用于描述需要的插件及是否开始插件。如果是在 plugin 内这个 plugin.ts 是插件元信息及依赖的声明，不会包含 enable，路径上也会直接在顶级，不放入 config 中去。

可以改个名字，不然和 application / framework 里的 `conifg/plugin.ts` 容易混淆

**Comment by JerrysShan** [comment]
可以，这里我调整下，主要先确定内容，才能扫描

**Comment by DuanPengfei** [comment]
@JerrysShan @hyj1991 这里是不是有点 Injectable 和 Inject 的感觉，一个用来声明，一个用来使用？如果是这样有个思路是，在 plugin 包内部使用根路径下的 plugin.meta.ts，在 application / framework 里使用 ${config 路径} 下的 plugin.ts。看看这样是否能够区分开？

**Comment by hyj1991** [comment]
> @JerrysShan @hyj1991 这里是不是有点 Injectable 和 Inject 的感觉，一个用来声明，一个用来使用？如果是这样有个思路是，在 plugin 包内部使用根路径下的 plugin.meta.ts，在 application / framework 里使用 ${config 路径} 下的 plugin.ts。看看这样是否能够区分开？

这样我觉得可以，不过或许应该直接叫 `meta.ts`？毕竟这个文件本身存在于 Plugin 里面，那么文件名不需要再声明 `plugin` 了。

**Comment by DuanPengfei** [comment]
> > @JerrysShan @hyj1991 这里是不是有点 Injectable 和 Inject 的感觉，一个用来声明，一个用来使用？如果是这样有个思路是，在 plugin 包内部使用根路径下的 plugin.meta.ts，在 application / framework 里使用 ${config 路径} 下的 plugin.ts。看看这样是否能够区分开？
> 
> 这样我觉得可以，不过或许应该直接叫 `meta.ts`？毕竟这个文件本身存在于 Plugin 里面，那么文件名不需要再声明 `plugin` 了。

嗯嗯，直接叫 meta.ts 是 ok 的，上下文能够保证语义明确，确实没必要多加个 plugin 的前缀。

**Comment by JerrysShan** [comment]
那名字就暂定 `meta.ts`, 内容如下，看下还有什么问题不
```typescript
export default {
    name: 'plugin1',
    dependencies: [
        {
            name: 'plugin2',
            package: '@artus/plugin2'
        },
        {
            name: 'plugin3',
            path: path.resolve(__dirname, 'plugin3')
        }
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            package: '@artus/plugin4'
        },
        {
            name: 'plugin5',
            path: path.resolve(__dirname, 'plugin5')
        }
    ]
}
```

**Comment by hyj1991** [comment]
只需要定义 `name` 即可，因为这个是具体的某个 Plugin 里的元信息，对于具体的 Plugin 来说，自身是不知道使用它的 application & framework 会从哪里引入它的依赖。

**Comment by DuanPengfei** [comment]
> 那名字就暂定 `meta.ts`, 内容如下，看下还有什么问题不
> 
> ```ts
> export default {
>     name: 'plugin1',
>     dependencies: [
>         {
>             name: 'plugin2',
>             package: '@artus/plugin2'
>         },
>         {
>             name: 'plugin3',
>             path: path.resolve(__dirname, 'plugin3')
>         }
>     ],
>     optionalDependencies: [
>         {
>             name: 'plugin4',
>             package: '@artus/plugin4'
>         },
>         {
>             name: 'plugin5',
>             path: path.resolve(__dirname, 'plugin5')
>         }
>     ]
> }
> ```

@JerrysShan 在使用场景上，应该只有 application 层面才会用到渐进式开发的插件，那是不是可以按照下面的情况分离开。
application 中定义依赖的插件 `${config 的路径}/plugin.ts`
```typescript
export default {
    dependencies: [
        {
            name: 'plugin2',
            package: '@artus/plugin2',
            enable: true,
        },
        {
            name: 'plugin3',
            path: path.resolve(__dirname, 'plugin3'),
            enable: true,
        }
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            package: '@artus/plugin4',
            enable: true,
        },
        {
            name: 'plugin5',
            path: path.resolve(__dirname, 'plugin5'),
            enable: true,
        }
    ]
}
```

framework 中定义依赖的插件 `${config 的路径}/plugin.ts`，与 application 的差异是，不提供 path 的能力，只允许写 package 值
```typescript
export default {
    dependencies: [
        {
            name: 'plugin2',
            package: '@artus/plugin2',
            enable: true,
        },
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            package: '@artus/plugin4',
            enable: true,
        },
    ]
}
```

在 plugin 内声明自己的元信息，meta.ts 内容，允许声明元信息、dependencies、optionDependencies，不提供 path 的能力，依赖中只允许写 package 值
```typescript
export default {
    name: 'xxxxxxxx',
    dependencies: [
        {
            name: 'plugin2',
            package: '@artus/plugin2',
            enable: true,
        },
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            package: '@artus/plugin4',
            enable: true,
        },
    ]
}
```

**Comment by noahziheng** [comment]
> @JerrysShan 只需要定义 `name` 即可，因为这个是具体的某个 Plugin 里的元信息，对于具体的 Plugin 来说，自身是不知道使用它的 application & framework 会从哪里引入它的依赖。

这个改动方式好像就只是把之前 artusPlugin 这个字段抽到单独的 `meta.ts` 里面了？那插件里面是否也会存在 `config/plugin.ts` 呢？

**Comment by noahziheng** [comment]
@DuanPengfei 这样的话岂不是 dependencies 相关信息要存在多份，config/plugin.ts 和 meta.ts 的已经没有本质区别了？

**Comment by DuanPengfei** [comment]
> @DuanPengfei 这样的话岂不是 dependencies 相关信息要存在多份，config/plugin.ts 和 meta.ts 的已经没有本质区别了？

- 在插件里，`meta.ts` 用于声明自己的元信息以及对其他插件的依赖关系，config 里面的文件用户声明支持的参数及设置默认值
- 在 application / framework 里，`${config 路径}` 里的 `plugin.ts` 用户定义需要的插件及是否开启，`${config 路径}` 里的其他文件用户配置，其实也包含插件自定义参数的配置。

重复的点是哪里我有点没 get 到 @noahziheng

**Comment by hyj1991** [comment]
@DuanPengfei 回到 Plugin 的使用方式上，对于 Application & Framework 来说，这种设计我觉得是可以的，描述了应用对插件的详细依赖信息：

```ts
export default {
    dependencies: [
        {
            name: 'plugin2',
            package: '@artus/plugin2',
            enable: true,
        },
        {
            name: 'plugin3',
            path: path.resolve(__dirname, 'plugin3'),
            enable: true,
        }
    ],
    optionalDependencies: [
        {
            name: 'plugin4',
            package: '@artus/plugin4',
            enable: true,
        },
        {
            name: 'plugin5',
            path: path.resolve(__dirname, 'plugin5'),
            enable: true,
        }
    ]
}
```

但是具体到插件中，它无需关心自己依赖的插件路径或者模块名称信息，只需要描述自己依赖的插件 `name` 即可：

```ts
export default {
    name: 'xxxxxxxx',
    dependencies: [
        {
            name: 'plugin2'
        },
    ],
    optionalDependencies: [
        {
            name: 'plugin4'
        },
    ]
}
```

写成对象可以是为了方便扩展，不然直接字符串即可

**Comment by hyj1991** [comment]
要尽量避免在 Plugin 的 meta.ts 中赋予和 Application & Framework 实际使用 Plugin 时重复的配置，否则还要处理两边配置冲突时的场景，这也是新的使用时把原来的 kv 模式 pkugin.ts 上次讨论修改为数组的原因，原本的 kv 其实 key 就是重复定义了 Plugin name

**Comment by DuanPengfei** [comment]
> @DuanPengfei 回到 Plugin 的使用方式上，对于 Application & Framework 来说，这种设计我觉得是可以的，描述了应用对插件的详细依赖信息：
> 
> ```ts
> export default {
>     dependencies: [
>         {
>             name: 'plugin2',
>             package: '@artus/plugin2',
>             enable: true,
>         },
>         {
>             name: 'plugin3',
>             path: path.resolve(__dirname, 'plugin3'),
>             enable: true,
>         }
>     ],
>     optionalDependencies: [
>         {
>             name: 'plugin4',
>             package: '@artus/plugin4',
>             enable: true,
>         },
>         {
>             name: 'plugin5',
>             path: path.resolve(__dirname, 'plugin5'),
>             enable: true,
>         }
>     ]
> }
> ```
> 
> 但是具体到插件中，它无需关心自己依赖的插件路径或者模块名称信息，只需要描述自己依赖的插件 `name` 即可：
> 
> ```ts
> export default {
>     name: 'xxxxxxxx',
>     dependencies: [
>         {
>             name: 'plugin2'
>         },
>     ],
>     optionalDependencies: [
>         {
>             name: 'plugin4'
>         },
>     ]
> }
> ```
> 
> 写成对象可以是为了方便扩展，不然直接字符串即可

嗯嗯，我理解了，其实在插件内部就是没得选，package 这个字段没意义了，name 就代表了是使用插件，可以这么理解吗？

如果是这么理解，有一个场景：插件的名称没有办法自动映射到包名，会出现这种情况吗?

**Comment by noahziheng** [comment]
@hyj1991 See Feishu

**Comment by hyj1991** [comment]
```ts
export default [
  {
     name: 'plugin2',
     package: '@artus/plugin2',
     enable: true,
  },
 {
     name: 'plugin3',
     path: path.resolve(__dirname, 'plugin3'),
     enable: true,
     optional: true
  }
]
```

**Comment by JerrysShan** [comment]
// 插件里面meta.ts
```
export default {
    name: 'xxxxxxxx',
    dependencies: ['plugin2'],
    optionalDependencies: ['plugin4']
}

```

// Application & Framework 中的${configDir}/plugin.ts

```
export default [
  {
     name: 'plugin2',
     package: '@artus/plugin2',
     enable: true,
  },
  {
     name: 'plugin4',
     path: path.resolve(__dirname, 'plugin4'),
     enable: true,
     optional: true
  }
]

```

**Comment by atian25** [comment]
跟一君聊了下，我不太明白，为什么要改为数组方式？

```ts
export default {
  plugin2: {
     package: '@artus/plugin2',
     enable: true,
  },
  plugin4: {
     path: path.resolve(__dirname, 'plugin4'),
     enable: true,
  }
}
```

有什么问题？ name 属性本来在 egg 里面就没必要写的。
key-value 的方式，还可以直接校验，避免数组里面写了同名的 name。

---

另外，我不建议为了改变为改变，一些这样也行那样也行的点，建议尽量不要改变 egg 之前的一些习惯。
因为这是在改变我们 7 年的用户心智，除非它真的非常的必要。否则未来 egg 和 artus 的生态是必然会走向割裂的。

**Comment by fengmk2** [comment]
按 egg 的经验放到 package.json 里面不行吗？我看 spec 也是这样定义的啊 https://github.com/artusjs/spec/blob/master/documentation/core/3.plugin.md#%E6%8F%92%E4%BB%B6%E4%BE%9D%E8%B5%96%E7%AE%A1%E7%90%86

除非之前的有特别大的问题要重新实现，否则我们不要再发散了，我们约定的4月底发布第一个版本的 artus，快没时间了。

**Comment by DuanPengfei** [comment]
> 跟一君聊了下，我不太明白，为什么要改为数组方式？
> 
> ```ts
> export default {
>   plugin2: {
>      package: '@artus/plugin2',
>      enable: true,
>   },
>   plugin4: {
>      path: path.resolve(__dirname, 'plugin4'),
>      enable: true,
>   }
> }
> ```
> 
> 有什么问题？ name 属性本来在 egg 里面就没必要写的。 key-value 的方式，还可以直接校验，避免数组里面写了同名的 name。
> 
> 另外，我不建议为了改变为改变，一些这样也行那样也行的点，建议尽量不要改变 egg 之前的一些习惯。 因为这是在改变我们 7 年的用户心智，除非它真的非常的必要。否则未来 egg 和 artus 的生态是必然会走向割裂的。

嗯嗯，这个技术上没倾向哈，当时应该是顺便提了一嘴写对象 key 和里面有重复的感觉，然后尝试写了一个数组的形式。但是看起来没解决什么问题，这块后面 PR 能看到不会有变动的。

**Comment by DuanPengfei** [comment]
> 按 egg 的经验放到 package.json 里面不行吗？我看 spec 也是这样定义的啊 https://github.com/artusjs/spec/blob/master/documentation/core/3.plugin.md#%E6%8F%92%E4%BB%B6%E4%BE%9D%E8%B5%96%E7%AE%A1%E7%90%86
> 
> 除非之前的有特别大的问题要重新实现，否则我们不要再发散了，我们约定的4月底发布第一个版本的 artus，快没时间了。

嗯嗯，这个是 ok 的，这个问题其实不涉及到 spec 改动哈，主要还是原来 Plugin 的 spec 里面有些 TODO，在开发时碰到了一些实现上不好搞不明确的问题，已经跟 @hyj1991 针对技术细节讨论了一些思路，等 PR 提上来再看。

**Comment by DuanPengfei** [comment]
> 按 egg 的经验放到 package.json 里面不行吗？我看 spec 也是这样定义的啊 https://github.com/artusjs/spec/blob/master/documentation/core/3.plugin.md#%E6%8F%92%E4%BB%B6%E4%BE%9D%E8%B5%96%E7%AE%A1%E7%90%86
> 
> 除非之前的有特别大的问题要重新实现，否则我们不要再发散了，我们约定的4月底发布第一个版本的 artus，快没时间了。

有关 4 月发第一版的目标肯定是一致的，大家都在爆肝中...

**Comment by noahziheng** [comment]
计划落地的版本（ #29 ）：

- pluginConfig（config/plugin.${env}.ts）仍维持 Spec 中的 K-V 结构
- pluginMeta 依照该 Issue 和 #29 中实现阶段的讨论，考虑暂时使用 `meta.yaml/meta.yml/meta.json` 的静态形式定义，格式与此前 `package.json` 中的 `artusPlugin` 字段趋同（optional 改为字段形式），如下：

```yaml
name: "plugin-a"
dependencies:
  - name: "plugin-b"
  - name: "plugin-c"
    optional: true
```

MetaData 的声明形式可通过类似 `plugin/impl.ts` 中的形式，上层框架通过对 BasePlugin 的不同实现来修改，用于兼容各自规范的插件，Artus 中搞的更理想些（静态化/单独管理）

TODO: 该部分后续需补入 Spec
