### ISSUE TITLE
[RFC] 插件元信息改为可选

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#35]
Reference: https://github.com/artusjs/core/pull/29/files/31d9b9caa40f910c6d3bd1d7daaf07f4cc8f7268..ad88b821e3fb310b57759a773ab80c5d76ef5f16#diff-adf063d6941507573873652a3078861a6310ab518ccf9b9227d0cebf1eddb8be

**Comment by hyj1991** [comment]
这点上大家既然都有历史包袱，那就改成既不强校验 `package.json`，也不强校验 `meta.yaml`，先读取 `meta`，没有再从 `package.json` 取好了，方便上层生态互通。

**Comment by DuanPengfei** [comment]
> 这点上大家既然都有历史包袱，那就改成既不强校验 `package.json`，也不强校验 `meta.yaml`，先读取 `meta`，没有再从 `package.json` 取好了，方便上层生态互通。

我们其实内心还是想追求生态能统一，这样的方式虽然后面插件生态能够通用，但是会不会给用户造成一些困扰？现在想想通过文档指导的方式应该能解，这样实现应该不会有啥问题。这个 @atian25 也看看吧。

**Comment by noahziheng** [comment]
已调整为基于 `main` + `meta.json`
