### ISSUE TITLE
enable plugin 可能存在的问题

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/core#37]
假设 plugin A 依赖了 B ， 项目中配置把 A disable ，plugin B 目前还是会被加载到。

貌似没什么副作用，只是加载了用不到的plugin；可能会出现边界case ，假设B 需要一些配置才能初始化，用户认为不使用A 了，也就不提供 B 的配置，但是 B 找不到配置，初始化报错

**Comment by hyj1991** [comment]
这个场景确实需要处理下

**Comment by hyj1991** [comment]
Reference: https://github.com/artusjs/core/pull/43

**Comment by noahziheng** [comment]
done
