### ISSUE TITLE
[RFC] 需要正确判断文件所属 loader

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#39]
判断 scanner 文件所属 loader 的逻辑：  https://github.com/artusjs/core/blob/master/src/scanner/scan.ts#L159

---

现有不会有副作用的判断：
* 对 `package.json` 以及 `artus-exception.yaml` 的 loader 类型判断，因为文件名称是固定的（不可能会误判）因此可以直接依赖文件名进行判断

* 对 `extension` 可以依靠用户自定义 ApplicationExtension 的注解来设置 reflect metadata 来进行判断，不依赖文件名

---

存疑可能带来副作用的判断：
* https://github.com/artusjs/core/blob/master/src/scanner/scan.ts#L177-L186

这部分配置相关的 loader 类型判断依赖文件名，这样会带来问题，比如用户自定义 `src/controller/config.ts` 也会被 scanner 扫描为 config 配置，可能带来问题

**Comment by noahziheng** [comment]
这个问题的核心还是我们对配置的定义希望保持之前的形式导致的，解法可能只能有：

1. 换配置写法，也上装饰器（Class）
2. 固定目录

cc @JerrysShan @DuanPengfei @Beace

**Comment by hyj1991** [comment]
> 这个问题的核心还是我们对配置的定义希望保持之前的形式导致的，解法可能只能有：
> 
> 1. 换配置写法，也上装饰器（Class）
> 2. 固定目录

目前我对 `extension` 这种支持导出 class 的用了装饰器进行支持，但是 config 这类配置，ts 装饰器只能作用于 class 不太方便使用

**Comment by hyj1991** [comment]
其实从设计上说，可以导出 class 的使用装饰器而非固定文件名是相对合理和符合 ts import 理念的，也许 config 类的配置在上层约定目录会更加合理一些？

**Comment by hyj1991** [comment]
cc @atian25 @whxaxes
