### ISSUE TITLE
loader机制的一些建议

### ISSUE THREAD

**Issue by wengeezhang** [artusjs/core#45]
目前看，scanner扫描出manifest后，交由loader来将item一一装载进container。

此时装载进去的是class。然后就开始触发hook启动服务。

然后等到请求进来，采取调用container.get去初始化一个实例，然后再根据scope决定是否缓存到md.value上。

这样看来，即使用户显示声明了scope=singleton，服务启动后，容器里面依然是没有实例的。

建议：
针对用户明确scope=singleton的，在loader的各个iml中，直接进行初始化。方便后续请求可以直接拿到。

注：目前看的是master分支代码，如果有分支正在处理或者我没有注意到的逻辑，请忽略！！

**Comment by JerrysShan** [comment]
感觉cotainer 里面可以做个优化，针对 `singleton` scope的，在set的时候就初始化

**Comment by wengeezhang** [comment]
大部分场景下，controller是会用到的。所以就做个优化，给这些99%会用到的做好准备。

有个例子：比如有些服务对性能要求较高，但是因为某些原因（用户内存重启设置较低、用户故意设置（在python中经常这么搞）），导致进程每天重启。此时新的请求的耗时就会出现稍微上涨。

**Comment by wengeezhang** [comment]
另外还有个想法：目前controller(singleton)-->service(execution)下，有两种处理方式：
1.将controller退化为execution（即在loader和get时，都根据meta信息临时转为execution）
2.controller不退化，依然保持singleton；在controller初始化自身property时，将其设置为getter（这样获取service时，就可以自由决定是否新建service实例）

**Comment by hyj1991** [comment]
core 没有定义协议，controller 如何实现是上层框架需要考虑的。

不过要使用 IoC `controller` 应该也只能是 execution，要不然就得纯 static 化，然后用 async local storage 注入 id，性能损耗估计比每个请求 new 都大。

**Comment by wengeezhang** [comment]
既然暴露了scope，用户就应该有权利决定。对于都是singleton的使用场景，我们也应该支持。

另外：controller只能是execution, 有点没太懂。可以通过proxy的方式，来实现（singleton->execution）的嘛

**Comment by DuanPengfei** [comment]
> 既然暴露了scope，用户就应该有权利决定。对于都是singleton的使用场景，我们也应该支持。
> 
> 另外：controller只能是execution, 有点没太懂。可以通过proxy的方式，来实现（singleton->execution）的嘛

core 其实是不理解什么 controller 的，这个需要在开发上层框架时，协议能力的地方去实现。我们可以通过这个场景，延伸出可能对 container 的需求，而不在 core 里边讨论 controller 本身哈。

**Comment by wengeezhang** [comment]
> 能力

controller这里是举个例子。在非http协议下，被注入对象也应该存在scope的概念吧。

**Comment by wengeezhang** [comment]
> > 另外还有个想法：目前controller(singleton)-->service(execution)下，有两种处理方式： 1.将controller退化为execution（即在loader和get时，都根据meta信息临时转为execution） 2.controller不退化，依然保持singleton；在controller初始化自身property时，将其设置为getter（这样获取service时，就可以自由决定是否新建service实例）
> 
> controller 的职责，需要感知 HTTP 请求中的参数，理论上就是请求相关的，执念在 singleton 上的原因可以给讲讲吗？

不是执念，是既然设计了scope，为啥又不支持singleton

**Comment by wengeezhang** [comment]
有些场景下，是全部singleton的，用户明确表示后，应该在容器里初始化好。如果通过请求触发，这个实现方式不太优雅

**Comment by DuanPengfei** [comment]
我这么理解下，看看对不对哈？其实这个不是执念在 controller 上，而是 container 没有提供 singleton 这个事，期望 container 有这个能力？

**Comment by wengeezhang** [comment]
> 我这么理解下，看看对不对哈？其实这个不是执念在 controller 上，而是 container 没有提供 singleton 这个事，期望 container 有这个能力？

对

**Comment by hyj1991** [comment]
对于 singleton 是不是要在容器时初始化，我认为需要看下社区普遍的 IoC 库实现再做决定，适当的，也可以给个配置是否在 `container.set` 时实例化。

**Comment by wengeezhang** [comment]
> 对于 singleton 是不是要在容器时初始化，我认为需要看下社区普遍的 IoC 库实现再做决定，适当的，也可以给个配置是否在 `container.set` 时实例化。

嗯，我去收集下。

**Comment by wengeezhang** [comment]
业界的一些实现：
* nestjs中集成的ioc：
  * 如果scope=default(即singleton)的，在启动阶段直接初始化。
  *  如果scope=request(即execution)的，每次请求到来时，进行初始化
* inversify业界独立的ioc:
  * 如果scope=singleton的，在第一次请求到来时，进行初始化并缓存，后续直接使用缓存的。
  * 如果scope=execution的，每次请求到来时，进行初始化
  
结论：
对于scope=singleton，是否要在container.set下初始化，目前来看有优化空间。可以先等等后面上层框架的实现。
至于是否加配置来决定是否在container.set下初始化，也先hold一下。

**Comment by hyj1991** [comment]
> 业界的一些实现：
> 
> * nestjs中集成的ioc：
>   
>   * 如果scope=default(即singleton)的，在启动阶段直接初始化。
>   * 如果scope=request(即execution)的，每次请求到来时，进行初始化
> * inversify业界独立的ioc:
>   
>   * 如果scope=singleton的，在第一次请求到来时，进行初始化并缓存，后续直接使用缓存的。
>   * 如果scope=execution的，每次请求到来时，进行初始化
> 
> 结论： 对于scope=singleton，是否要在container.set下初始化，目前来看有优化空间。可以先等等后面上层框架的实现。 至于是否加配置来决定是否在container.set下初始化，也先hold一下。

@JerrysShan 看来我们可以给一个配置来控制下 `singleton` 的初始化时机，适配不同的上层

**Comment by wengeezhang** [comment]
> > 业界的一些实现：
> > 
> > * nestjs中集成的ioc：
> >   
> >   * 如果scope=default(即singleton)的，在启动阶段直接初始化。
> >   * 如果scope=request(即execution)的，每次请求到来时，进行初始化
> > * inversify业界独立的ioc:
> >   
> >   * 如果scope=singleton的，在第一次请求到来时，进行初始化并缓存，后续直接使用缓存的。
> >   * 如果scope=execution的，每次请求到来时，进行初始化
> > 
> > 结论： 对于scope=singleton，是否要在container.set下初始化，目前来看有优化空间。可以先等等后面上层框架的实现。 至于是否加配置来决定是否在container.set下初始化，也先hold一下。
> 
> @JerrysShan 看来我们可以给一个配置来控制下 `singleton` 的初始化时机，适配不同的上层

嗯，这个思路可以。

**Comment by noahziheng** [comment]
injection 已通过 eager 支持这一属性，按需使用即可
