### ISSUE TITLE
[RPC] Scanner 环境有关

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#49]
## 背景

目前的 Env 无关的 Manifest 带来扫描和启动阶段的过重逻辑，也出现了诸如多环境 plugin 顺序计算无解的实现问题

因此需要更改为 Scanner 阶段环境有关，即只扫描计算 Env 下对应的 Manifest

## 设计

* Scanner 入口新增 Env 数组配置
* 单个 Env 扫描环境有关，返回对应环境下的 Manifest
* Scanner 根据入口的 Env 数组，返回对象包含

`Scanner.property.scan` 方法增加入口参数 Env 数组，以下为伪代码演示：

```ts
const scanner = new Scanner({ needWriteFile: false });
const result = await scanner.scan(path.resolve(__dirname, './'), { env: ['dev', 'test'] });
```

返回的 `result` 对象形如：

```js
{
  dev: Manifest,
  test: Manifest
}
```

更多的，如果允许将生成 Manifest 写文件：

```ts
const scanner = new Scanner({ needWriteFile: true });
await scanner.scan(path.resolve(__dirname, './'), { env: ['dev', 'test'] })
```

则会在当前目录下生辰 `manifest.dev.json` 以及 `manifest.test.json`。

**Comment by hyj1991** [comment]
cc @atian25 @DuanPengfei @noahziheng

**Comment by hyj1991** [comment]
使用 Env 数组作为入口参数而不是直接基于 `process.env` 处理的原因是希望 `Scanner` 本身不带状态

**Comment by DuanPengfei** [comment]
@hyj1991 如果这样处理，看起来是支持把所有环境都扫描出来，然后生成多个 manifest.${env}.json 的，所以思路上还是可以一次构建，多次使用的，可以这么理解吗？

如果可以的话，那真要一次扫描把多个 manifest 生成出来，扫描里面 config 要单独处理下吧，毕竟我们得根据 config 里面写了多少个去决定要传给 scanner 的 env 数组有多少个。如果考虑到部署单元，这个环境变量在运行时才有，构建时怎么拿到呢？

**Comment by hyj1991** [comment]
> 扫描里面 config 要单独处理下吧

扫描阶段其实不需要处理 conifg，扫描的目的是得到一份应用启动期完整 manifest，现在真正和 Env 强相关且会影响到 manifest 是否加载到错误文件的是 plugin 和 framework config，因为遍历错误 Env 的 plugin 和 framework 目录会导致当前 Env 下应用不需要的文件被加载进来。

相对而已，应用本身配置的多个环境 Env 影响并不大。
