### ISSUE TITLE
[RFC] hook涉及的装饰器命名调整

### ISSUE THREAD

**Issue by wengeezhang** [artusjs/core#52]
目前通过@ApplicationExtension和@ApplicationHook来声明hook，供后续扫描器加载hook文件，并注册到lifemanager中。

extension会增加理解成本，让人误以为是业务能力的扩展。

**调整理由如下：**
1. 开源后，增加开发者的理解成本
2.这个装饰器是暴露出去，会增加用户的理解门槛

**调整方案：**
1. @ApplicationExtension调整为 @ApplicationHookUnit
2. @ApplicationHook 调整为 @ApplicationHookRegister  （或者名字不调整也行）
3. 其他内部实现涉及的，名字都调整下

**Comment by hyj1991** [comment]
`Unit` 这个后缀也感觉有点奇怪

**Comment by wengeezhang** [comment]
嗯，命名可以微调下

**Comment by wengeezhang** [comment]
ApplicationExtension目前是用来识别 是否是hook文件,供扫描器使用的。如果没有其他作用，调整为下面的这个方案怎么样：

@ApplicationExtension调整为 @ApplicationHook
@ApplicationHook 调整为 @ApplicationHookHandler

**Comment by hyj1991** [comment]
其实我觉得没必要一定要绑定 `Application`，比如对生命周期的钩子叫 `LifecycleExtension` 或者 `LifecycleHook` 也可以，表示针对生命周期的自定义扩展，`Application` 绑定的概念和方法名 / 变量名在目前的框架里太多了

**Comment by wengeezhang** [comment]
> 其实我觉得没必要一定要绑定 `Application`，比如对生命周期的钩子叫 `LifecycleExtension` 或者 `LifecycleHook` 也可以，表示针对生命周期的自定义扩展，`Application` 绑定的概念和方法名 / 变量名在目前的框架里太多了

嗯，我也赞同去掉Application。但是最好别叫LifecyleExtension。用LifecyleHook*比较好

**Comment by wengeezhang** [comment]
经过讨论，先按照如下方案调整：
1. @ApplicationExtension调整为 @LifecycleHookUnit
2. @ApplicationHook 调整为 @LifecycleHookHandler
3. 其他内部实现涉及的，名字对应调整下

**Comment by DuanPengfei** [comment]
> 经过讨论，先按照如下方案调整：
> 
> 1. @ApplicationExtension调整为 @LifecycleHookUnit
> 2. @ApplicationHook 调整为 @LifecycleHookHandler
> 3. 其他内部实现涉及的，名字对应调整下

@wengeezhang 这里 Unit 后缀还有必要吗？

**Comment by noahziheng** [comment]
@DuanPengfei 因为 Hook 其实还有 FP 方案，Application.registerHook() 所以逻辑上 Hook 其实是指“函数”，用 它来作为类装饰器可能会引入歧义

**Comment by DuanPengfei** [comment]
> @DuanPengfei 因为 Hook 其实还有 FP 方案，Application.registerHook() 所以逻辑上 Hook 其实是指“函数”，用 它来作为类装饰器可能会引入歧义

按逻辑 FP 里 register 应该对应到的是 handler 这一层吧？那是不是 Application.registerHookHandler 比较合理？

**Comment by wengeezhang** [comment]
> > @DuanPengfei 因为 Hook 其实还有 FP 方案，Application.registerHook() 所以逻辑上 Hook 其实是指“函数”，用 它来作为类装饰器可能会引入歧义
> 
> 按逻辑 FP 里 register 应该对应到的是 handler 这一层吧？那是不是 Application.registerHookHandler 比较合理？

1.cycle的C大写  可以。
2.目前仅仅extension改lifecycle，就涉及很多地方，我先按照“@LifecycleHookUnit+@LifecycleHookHandler”改。至于后续是否要微调名字，就比较好办了。

**Comment by DuanPengfei** [comment]
> > > @DuanPengfei 因为 Hook 其实还有 FP 方案，Application.registerHook() 所以逻辑上 Hook 其实是指“函数”，用 它来作为类装饰器可能会引入歧义
> > 
> > 
> > 按逻辑 FP 里 register 应该对应到的是 handler 这一层吧？那是不是 Application.registerHookHandler 比较合理？
> 
> 1.cycle的C大写 可以。 2.目前仅仅extension改lifecycle，就涉及很多逻辑，我先按照“@LifecycleHookUnit+@LifecycleHookHandler”改。至于后续是否要微调名字，就比较好办了。

每次改动不应该是字符串替换？逻辑也需要改动？

**Comment by hyj1991** [comment]
`@LifecycleHookUnit` 其实已经表名此 class 里面是包含 `lifecycle hook` 的集合了，再给其成员方法注解名里的 `Lifecycle` 以及 `Hook` 严格说也是冗余信息。

```ts
@LifecycleHookUnit()
export default class MyLifecycleHookUnit {
  @Handler()
  didLoad(){
    
  }
}
```

这样冗余信息更少一些

**Comment by DuanPengfei** [comment]
> `@LifecycleHookUnit` 其实已经表名此 class 里面是包含 `lifecycle hook` 的集合了，再给其成员方法注解名里的 `Lifecycle` 以及 `Hook` 严格说也是冗余信息。
> 
> ```ts
> @LifecycleHookUnit()
> export default class MyLifecycleHookUnit {
>   @Handler()
>   didLoad(){
>     
>   }
> }
> ```
> 
> 这样冗余信息更少一些

如果是业务代码，上下文存在确实减少冗余信息更好；不过框架提供的 decorator 感觉还是得冗余一下，明确一些，Handler 这个词太通用了。

**Comment by wengeezhang** [comment]
> > `@LifecycleHookUnit` 其实已经表名此 class 里面是包含 `lifecycle hook` 的集合了，再给其成员方法注解名里的 `Lifecycle` 以及 `Hook` 严格说也是冗余信息。
> > ```ts
> > @LifecycleHookUnit()
> > export default class MyLifecycleHookUnit {
> >   @Handler()
> >   didLoad(){
> >     
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样冗余信息更少一些
> 
> 如果是业务代码，上下文存在确实减少冗余信息更好；不过框架提供的 decorator 感觉还是得冗余一下，明确一些，Handler 这个词太通用了。

嗯，这里确实有必要冗余以下

**Comment by wengeezhang** [comment]
> > > > @DuanPengfei 因为 Hook 其实还有 FP 方案，Application.registerHook() 所以逻辑上 Hook 其实是指“函数”，用 它来作为类装饰器可能会引入歧义
> > > 
> > > 
> > > 按逻辑 FP 里 register 应该对应到的是 handler 这一层吧？那是不是 Application.registerHookHandler 比较合理？
> > 
> > 
> > 1.cycle的C大写 可以。 2.目前仅仅extension改lifecycle，就涉及很多逻辑，我先按照“@LifecycleHookUnit+@LifecycleHookHandler”改。至于后续是否要微调名字，就比较好办了。
> 
> 每次改动不应该是字符串替换？逻辑也需要改动？

这次调整，因为loader类型有一个是extension需要调整为life-cycle。很多地方都是用字符串写的，要替换为Symbol。
但是现在看有些地方对loader还有排序，所以需要调整一些逻辑。

现在的策略调整以下，先不改成symbol了，分成两步走。这个issue只改字符串。改成symbol的，另外拉个issue好了

**Comment by wengeezhang** [comment]
小结：

**一.背景**
当前生命周期hook的声明是通过@ApplicationExtension和@ApplicationHook完成的。因为这两个装饰器是暴露给业务开发的，extension的命名会和“业务能力扩展”混淆，增加理解成本。

**二.最终调整方案**
1.@ApplicationExtension --> @LifecycleHookUnit
2.@ApplicationHook --> @LifecycleHook
3. extension --> lifecycle-hook-unit _（loader type）_

**三.说明**
1.@LifecycleHookUnit的用途

用来装饰一个class，这个class 所在的文件，将会通过“lifecycle专属”loader进行加载。它下面的所有property method（加了hook装饰器）将被注册进lifemanager。
取“unit”，是为了突出“集合”，“一组”这个意思。

```ts
@LifecycleHookUnit()
export default class MyLifecycle implements ApplicationLifecycle {
  @LifecycleHook()
  async didLoad() {..}

  @LifecycleHook()
  async beforeClose() {..}
}
```
2.@LifecycleHook的用途

用来装饰class下的一个property method，表示这个方法将被注册到lifemanager，供后续emit调用。和fp下的application.registerHook()作用相同。

3.本来打算把@ApplicationHook 调整为 @LifecycleHookHandler的，为什么现在调整为@LifecycleHook了呢？

由于artus/core中的基类 interface Application有一个方法registerHook，涉及面太广。为了保持统一，所以针对method的装饰器，统一以hook结尾来表示，不加handler

4.loader type的常量，本来打算由extension改为lifecycle的，为什么要调整为lifecycle-hook-unit？

本来是打算调整为lifecycle的。因为生命周期的东西有很多，而这里是hook方向，为了精确和后续扩展，改为lifecycle-hook-unit，表示此类加载器就是加载生命周期的hook的。

5.constraints.ts中的一些常量（如：HOOK_CONSTRUCTOR_PARAMS）调整

这部分常量是以HOOK_开头的，但是和hook没有关系，所以将这部分常量统一去掉HOOK_。

**Comment by wengeezhang** [comment]
@hyj1991 @noahziheng 对应的代码已经重新提交，pr在 https://github.com/artusjs/core/pull/55
