### ISSUE TITLE
[RFC] 统一规范下文件、文件夹的命名规范

### ISSUE THREAD

**Issue by DuanPengfei** [artusjs/core#56]
当前文件、文件夹的命名比较随意，小写加中划线，小驼峰等都存在，单数负数也都存在。需要一个统一规范。

提个建议如下：
- 文件、文件夹，小写字母加下划线 `a_b_c` `d_e_f.ts`
- 采用单数形式，`controller` `constant.ts` 而不是 ~~`controllers` `constants.ts`~~

**Comment by Beace** [comment]
代码注释是不是也适当加点 😅

**Comment by wengeezhang** [comment]
目前几个业界推出的规范中，其中关于文件命名的有：
* 谷歌js:https://google.github.io/styleguide/jsguide.html#file-name
  * 全部小写，用_或者-分割
* 腾讯alloy: http://alloyteam.github.io/CodeGuide/#project-naming
  * 全部采用小写方式， 以下划线分隔。

建议约束如下：
* 全部小写，用_分割

**Comment by wengeezhang** [comment]
目前config文件夹，只会出现在test目录下。

artus lib不会有，还是遵循：全部小写，_分割，首字母不可以是_

**Comment by hyj1991** [comment]
我觉得多单词用驼峰或者 `-` 隔离，`_` 有点非主流

**Comment by wengeezhang** [comment]
> 我觉得多单词用驼峰或者 `-` 隔离，`_` 有点非主流

驼峰肯定不建议。目前看存量很多文件用的是-。可以考虑调整为-,把其他少数驼峰的改下。

**Comment by hyj1991** [comment]
驼峰不建议的原因是？

**Comment by wengeezhang** [comment]
跨平台问题，有些大小写不敏感。

**Comment by hyj1991** [comment]
对，这样的话确实得限定小写来规避掉此类问题，分割我投 `-` 一票

**Comment by noahziheng** [comment]
> 我觉得多单词用驼峰或者 `-` 隔离，`_` 有点非主流

Golang/Python/CPP 这一系都惯常使用 `_` 分割，驼峰一般是 JVM 语言爱用，不过 JavaScript 语境下我也投 `-`

**Comment by wengeezhang** [comment]
最新建议：

* 全部小写，用-分割,比如：a-b-c.js
* 首字母不可以是-

注意：业务仓库（test）下的config文件夹下的文件是特殊文件，有专属的文件格式约定。

_（另外，nginx头部key默认不支持_, 极端情况下业务使用文件名作为header，会导致信息丢失）_

**Comment by JerrysShan** [comment]
我投全部小写 +`_` 一票 ,例如 `home_controller.ts`

**Comment by atian25** [comment]
全部单数 + 全部小写 + `_` + 尽量少用那么长的词

**Comment by DuanPengfei** [comment]
投【单数】+【全部小写】+ `_`

**Comment by Beace** [comment]
投【单数】+【全部小写】+ _

**Comment by wengeezhang** [comment]
基于私下讨论和投票结果，结论如下：

1.一律采用小写
2.采用单数形式
3.分隔符采用_

**Comment by XadillaX** [comment]
下划线 +1
