### ISSUE TITLE
Release 1.0.0@beta

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#61]
看了下目前的主要功能已经合并和局部的重构，可以先 release 一个 1.0.0 beta 版本

**Comment by hyj1991** [comment]
cc @noahziheng @DuanPengfei

**Comment by noahziheng** [comment]
+1，看下是走 Actions 发还是人工操作一把

**Comment by hyj1991** [comment]
使用 Actions 自动化发布吧，人工容易出错，自动化流程只有走一遍 OK 就不会有问题

**Comment by noahziheng** [comment]
[撒花]v1.0.0-beta.0 现已发布
https://github.com/artusjs/core/releases
https://www.npmjs.com/package/@artus/core

**Comment by fengmk2** [comment]
恭喜各位，这是历史性一刻。
