### ISSUE TITLE
[RFC] Loader 增强

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#66]
## 背景

Scanner 阶段扫描文件根据自定义 Loader + 内置 Loader 的组合判断应用所有的文件分别应该被哪种 Loader 加载，其中自定义 Loader 尚存在一些使用问题：
* 需要手动 `import`，对于自定义 Loader 分散在多层上层框架封装中的场景下对应的 Scanner 使用不友好

因此需要内置在扫描期实现一个自动加载自定义 Loader 的功能，并且在扫描其余应用文件之前执行。

另外目前的 `DefineLoader` 实现的 `is` 方法仅对符合条件的扫描文件返回了本 Loader 名称，稍显简单，考虑在 `Manifest` 属性中添加一个自定义 Slot 对象：`Record<string, any>`，用来存储自定义扫描期处理的元信息给 `load` 逻辑消费，进一步减少可能存在的启动期的计算消耗。

## 实现

因此初步考虑 Loader 的增强如下能力：
* Scanner 扫描提供前置方法，内置对自定义 Loader 的公共处理
* Loader 本身增加一个 `handle` 方法，开放传入当前的 `scanner` 实例增强自定义 Loader 的能力

**Comment by hyj1991** [comment]
cc @atian25 @noahziheng @DuanPengfei

**Comment by atian25** [comment]
这几点我补充下：

- 一般会在 Framework 里面去定义一些 loader 规范，那在多层 Framework 的场景下， scanner 在扫描期如何找到这些 loader，从而可以生成正确的 manifest
- `DefineLoader` 目前看是一个比较特殊的装饰器，或者说注解更适当，它是唯一一个在构建期和启动期都会使用到的。
  - 还有其他有这样双重身份的装饰器么？
  - 扫描期的时序是怎么样的？如何初始化的？
  - DefineLoader 目前是 `is` 会在扫描期执行，但 constructor 的 container 好像又不会，那 `is` 是不是应该是一个 static 方法？
- `DefineLoader` 既然是一个构建期行为，那是不是可以再进一步，它可以在构建期对对应的文件做一些分析（如 AST 啥的），对应的结果，可以保存回到 manifest 里面，从而可以让它自己在启动期可以消费到。也就是除了 `is` 是不是还要加个方法。

**Comment by noahziheng** [comment]
@atian25 
- 目前 Custom Loader 需要静态被 import，这也是这个 Issue 存在的意义
- 目前没有类似的装饰器，是比较特殊的，扫描期时序通过 ScannerOptions.loaderListGenerator 参数定制，初始化过程目前无意义（空 Container，仅调用 is()）
- Loader.is 可以，也有计划改成 static，之前考虑可能用到 container，但合并后发现这个地方过度设计了
- 这个地方确实可以再增强，但是要有实际的需求去支撑，不好说能直接设计成通用的机制

**Comment by noahziheng** [comment]
@hyj1991 
- 之前沟通过，Loader 这个东西基于蛋鸡理论，自动加载可能会挖坑，不如全静态处理，我觉得倒是可以考虑优化静态 import 、定制 Scanner 时序这个行为的编程界面
- 如上的最后一条，还是要拿出确实的需求是不是好一点，太通用的机制必要性和后续的黑盒会不会比较迷惑（PS: 我觉得 any 很蛋疼）

**Comment by hyj1991** [comment]
@noahziheng 有需求，比如我在定制上层框架的时候，对某类文件扫描处理完后希望往当前 loader 类型的 items 列表里插入一些 ManifestItem（或者替换），现有的机制是不支持的

**Comment by noahziheng** [comment]
> @noahziheng 有需求，比如我在定制上层框架的时候，对某类文件扫描处理完后希望往当前 loader 类型的 items 列表里插入一些 ManifestItem（或者替换），现有的机制是不支持的

@hyj1991 我的意思就是按照具体的需求细化，向这个可以考虑加 afterScan Hook，提供这么泛化的 `Record<string, any>` 感觉不是很好

**Comment by noahziheng** [comment]
@hyj1991 @atian25 

其实现阶段的 Loader 设计上存在一些奇怪的点，DefineLoader 原本只是内部语法糖，和其他的 Metadata Decorator 完全不同，现在也要对外作为 CustomLoader 的一部分是不合适的。

可能要调整一下，Loader 通过静态传递类列表，Scanner + Loader 在构建期也做一个完整的 Lifecycle 做定制，是否更合理？

**Comment by hyj1991** [comment]
Hook 我认为可以，即 Scanner 中每一个文件扫描完成的前后钩子可以提供，也能解决这种需求。

**Comment by hyj1991** [comment]
没太明白类列表的意思，是说不用 `@DefineLoader`  来定义加载器？而是显式传递加载器的 class 类么

**Comment by noahziheng** [comment]
> 没太明白类列表的意思，是说不用 `@DefineLoader` 来定义加载器？而是显式传递加载器的 class 类么

对的

**Comment by hyj1991** [comment]
显式传递加载器 Class 列表，也需要有个公共逻辑来自动扫描框架或者插件里的自定义加载器，否则使用起来会比较麻烦

**Comment by noahziheng** [comment]
> 显式传递加载器 Class 列表，也需要有个公共逻辑来自动扫描框架或者插件里的自定义加载器，否则使用起来会比较麻烦

这个部分我是觉得比较奇怪，这个部分就是为了决定扫描的时候用什么 loader，然后还再扫描，就...比较迷惑

而且这样是不是需要 walk 两遍，先拿到 Custom Loader 列表，再走现在的 scan

**Comment by DuanPengfei** [comment]
> 

@atian25 我对 @DefineLoader 这个注解其实是有点困惑的，这个注解的功能和逻辑其实未必一定要以注解形式实现，而且以注解实现看起来也跟其他注解的能力差异很大。

对 Custom Loader 的定位，我是这么想的。首先，如果没有 CustomLoader，我作为一个业务框架定制者，基于 Artus Core，我的做法是，利用 Lifecycle 的能力，抄 Artus Scanner 的方式，扫描我特定的文件，并生成符合 manifest 规范的描述，然后加到 manifest 中去（这种对于仍旧是 JS 逻辑是可行的）；对于 YAML 这种，比如提供了通过 YAML 描述可以自动生成 HTTP Server，并且不行提供 generate JS 文件的方式，就想启动时做，让用户看不到 JS 代码。那也可以按照这个思路，在构建时生成临时产物，再走自定义扫描逻辑。

那么顺着这个思路，自定义扫描比较通用，提供了 CustomLoader。那 Custom Loader 从概念上理解应该影响的是构建阶段，要在我们内置 Scanner 的流程中去扩展或者打断等等操作从而影响 manifest。那是不是就应该在 Scanner 也按照生命周期的思路，制定好规则，自定义的 Loader 就按照规则去在每个阶段读文件，转换，然后生成 manifest 描述就够了。Loader 就还是运行时概念，该怎么加载就还是怎么加载。这里 CustomLoader 其实跟 Loader 没有什么强制关系？

**Comment by hyj1991** [comment]
@DuanPengfei 

> 对 Custom Loader 的定位，我是这么想的。首先，如果没有 CustomLoader，我作为一个业务框架定制者，基于 Artus Core，我的做法是，利用 Lifecycle 的能力，抄 Artus Scanner 的方式，扫描我特定的文件

**抄重复的逻辑** 本身就背离框架的初衷了，`core` 应该提供便捷的渠道给上层使用者，而不是让他自己去 core 中拷贝相似的逻辑

**Comment by DuanPengfei** [comment]
> @DuanPengfei
> 
> > 对 Custom Loader 的定位，我是这么想的。首先，如果没有 CustomLoader，我作为一个业务框架定制者，基于 Artus Core，我的做法是，利用 Lifecycle 的能力，抄 Artus Scanner 的方式，扫描我特定的文件
> 
> **抄重复的逻辑** 本身就背离框架的初衷了，`core` 应该提供便捷的渠道给上层使用者，而不是让他自己去 core 中拷贝相似的逻辑

不要介意这个，我是习惯把一个事情提出的背景和思考的思路写出来，那里主要想表达的是我对为什么会出现 Custom Loader 的理解哈，跟技术无关，也是认可 Custom Loader 这个理念的。😄

**Comment by DuanPengfei** [comment]
> > 
> 
> @atian25 我对 @DefineLoader 这个注解其实是有点困惑的，这个注解的功能和逻辑其实未必一定要以注解形式实现，而且以注解实现看起来也跟其他注解的能力差异很大。
> 
> 对 Custom Loader 的定位，我是这么想的。首先，如果没有 CustomLoader，我作为一个业务框架定制者，基于 Artus Core，我的做法是，利用 Lifecycle 的能力，抄 Artus Scanner 的方式，扫描我特定的文件，并生成符合 manifest 规范的描述，然后加到 manifest 中去（这种对于仍旧是 JS 逻辑是可行的）；对于 YAML 这种，比如提供了通过 YAML 描述可以自动生成 HTTP Server，并且不行提供 generate JS 文件的方式，就想启动时做，让用户看不到 JS 代码。那也可以按照这个思路，在构建时生成临时产物，再走自定义扫描逻辑。
> 
> 那么顺着这个思路，自定义扫描比较通用，提供了 CustomLoader。那 Custom Loader 从概念上理解应该影响的是构建阶段，要在我们内置 Scanner 的流程中去扩展或者打断等等操作从而影响 manifest。那是不是就应该在 Scanner 也按照生命周期的思路，制定好规则，自定义的 Loader 就按照规则去在每个阶段读文件，转换，然后生成 manifest 描述就够了。Loader 就还是运行时概念，自定义的 Loader 有名字，manifest 也生产好了，运行时就通过自定义 Loader 去加载。
> 
> 总结一下：
> 
> * 明确成**「构建」「运行」**这两个大分类
> * **Scanner** 阶段也提供 **Hook**
> * 一个 Plugin 或 Framework 在**「构建」阶段**可以**使用 hook 影响 manifest**
> * 一个 Plugin 或 Framework **提供一个 Loader（应该是个提供功能逻辑的 class）**，**在「运行」阶段根据 manifest 去加载**
> * 问题：**如何提供一个 Loader class**，这个时候可以通过**注解，标注是一个 Loader**，扫描阶段碰到这种注解的也会加载到 manifest 中去。**运行阶段，跟 config 等一样特殊处理，有个专门处理自定义 Loader 的环节，调用自动以 Loader 让他去加载。**（可能会出现与**默认 Loader 的冲突问题**？比如对同一个装饰器标注的 class 处理逻辑不同？这种要看看优先级？）
> 
> @noahziheng @hyj1991 cc

说的有点乱，可能需要代码才能讲清楚 😂

**Comment by noahziheng** [comment]
@DuanPengfei @atian25 @JerrysShan 
我和 @hyj1991 语音对了一下，先不发散来看，大概有下面的共识：

- Loader 需要支持在外层定义 Custom Loader，逻辑上确实应当可以同时影响扫描（构建）和运行时
- Scanner 中需要支持对 CustomLoader 的扫描行为（尤其在 Framework 多层递归的场景下），可以类比 Config 的实现，考虑到 Scanner 需要承担的东西已经足够多，应该梳理一下逻辑做重构

要达到当前 Issue 中的诉求，我们需要做下面四个改动：

- DefineLoader 改为 Metadata 实现，register 行为单独在使用 LoaderFactory 前完成，避免歧义 @noahziheng DL0513
- Scanner 的扫描行为需要被重构 @hyj1991 DL0516
  - 加入对 Custom Loader 的扫描，初步考虑和 Config 一样走限定路径
  - loaderDir/configDir 应当支持逐插件/框架在 Meta 中配置
  - 逻辑需要被拆分成块，并顺便加入 `Hook` 支持，形式和命名需要注意不能和 Application Lifecycle 冲突（有歧义）
- Loader 中构建时及运行时需要加入更多联动，借助 Manifest 实现静态数据的共享 @noahziheng DL0516
  - 考虑到目前是在一个类里，尝试直接加入特定的 `storeData` 字段并加入序列化反序列化机制
  - 兜底提供 `Record<string, any>` 作为 ManifestItem 中的 slot，要求 Loader 开发者自己解析

在以上改动 PR 提交前，当前 Issue 我们先不进行发散的讨论吧，当然对于代码实现及思路的意见还是发出来

**Comment by wengeezhang** [comment]
>   * 加入对 Custom Loader 的扫描，初步考虑和 Config 一样走限定路径
>   * loaderDir/configDir 应当支持逐插件/框架在 Meta 中配置

可不可以不再引入特殊的文件夹，怕以后hold不住。

如果调整为这样呢：
* 第一次：遍历文件，生成manifest。这一次不挂载item的loader属性，仅仅做两个目的：
  * 生成manifest
  * 识别出个性化loader文件，放到LoadFactory的loaderClazzMap中，供后续使用
* 第二次：遍历manifest，对每一个item，设置loader信息
  * 因为个性化loader已经放到LoadFactory中了
  
@noahziheng @hyj1991

**Comment by wengeezhang** [comment]
目前lifecycle的loader，已经采用@LifecycleUnit来识别了。个性化loader可以采用@CustomeLoader来识别。

否则当时引入@LifecycleUnit的初衷就没啥用了（为了避免设置个性化lifecycle文件夹）

**Comment by noahziheng** [comment]
@wengeezhang 逻辑上可行也合理，不过这样的话之前在 Loader 里加扫描期钩子的实现思路要重新看看

不用引入新的装饰器，DefineLoader 已经也改成 metadata 的形式了

@hyj1991 你看呢

**Comment by DuanPengfei** [comment]
> @wengeezhang 逻辑上可行也合理，不过这样的话之前在 Loader 里加扫描期钩子的实现思路要重新看看
> 
> 不用引入新的装饰器，DefineLoader 已经也改成 metadata 的形式了
> 
> @hyj1991 你看呢

我也是比较倾向依据 decorator 这个形式，尽量少得依赖文件结构。

**Comment by hyj1991** [comment]
这个做法可以，我也比较倾向于使用 lifecycle 这种形式，不要约定文件夹，但是之前有蛋和鸡的问题，现在如果只是增加一遍的扫描，我认为可以接受
