### ISSUE TITLE
怎么区分特殊类

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/core#67]
按照现在 Artus 的实现，我们虽然一直强调和目录无关，但是我们还是对一些类需要做区分，然后在挂载的时候做处理，现在遇到的 case 有：
- @artus/core 
    - LifecyleHook Class ，因为生命周期的原因，需要最先处理，注册各个 lifecycle hook
- 上层 web 框架
  - Controller Class ，携带了路由的元信息， 路由注册的时候需要把这些类批量获取出来，注册路由
  - Middleware Class ，注册中间件的时候，需要把这部分类批量拿出来，然后注册中间件
- others ...

现在的问题是把这些类托管给容器后，怎么批量获取这些类？

**Comment by JerrysShan** [comment]
一种思路是通过装饰器打标，IoC 容器扩展根据标签批量获取的能力

**Comment by wengeezhang** [comment]
伪代码如下
```ts
// Container下的set
public set(classDecorator, classInfo) {
  if(this.registryMap[classDecorator]){
    this.registryMap[classDecorator].push(classInfo)
  } else {
    this.registryMap[classDecorator] = [classInfo]
  }
}
```

这里用的一个新registryMap来管理做示例。也可以用现在的registry来再切分以下。

**Comment by DuanPengfei** [comment]
@hyj1991 @noahziheng cc

**Comment by hyj1991** [comment]
> 一种思路是通过装饰器打标，IoC 容器扩展根据标签批量获取的能力

这个方式可以，但是使用体验上可以简单一些，而且也要考虑到获取的效率，比如可以在 `@Injectable` 的时候增加一个参数判断在 `container.set` 的时候是否需要批量添加到对应的属性集合中：

```ts
@Injectable({ set: 'controller' })
class HomeController {
}
```

这样通过容器操作的话可以直接使用 `container.get({set: 'controller'})` 来批量获取

更多的，没有这个额外属性的 class 就还是使用原来的方式

**Comment by JerrysShan** [comment]
set 集合
