### ISSUE TITLE
[RFC] 增加统一风格的 Logger 实现

### ISSUE THREAD

**Issue by noahziheng** [artusjs/core#72]
在内部封装过程中，我们发现，对于 Runtime 这一定位来说，将用户和框架通常都会使用的日志、打点、追踪、异常处理逻辑（可观测性实现）进行接口级别的统一是有必要的，在目前的 Artus 模型中：

- 异常处理（Expection）已经写入 Spec 并在 1.0.0 中按规范实现
- 打点（Metrics）、追踪（Tracing）受各自公司架构限制（与社区 OpenTelementry/OpenTracing 不统一），很难定出标准接口，初步评估只能通过预留钩子实现
- 日志模块（Logger） 可以进行抽象，并参考 Node.js Console 模块定义标准 API

综上，建议如下：

- 在 Core 内增加可被覆盖式扩展（与 Trigger 趋同）的 Logger 标准实现
- 对 Level、Options 确立标准 Interface 
- 反向在 Spec 下次修订中加入对于 日志 Logger 的规范文本

**Comment by DuanPengfei** [comment]
cc @hyj1991
