### ISSUE TITLE
[RFC] manifest 绝对路径更改为相对路径

### ISSUE THREAD

**Issue by hyj1991** [artusjs/core#79]
## 背景

manifest 中目前记录扫描文件的为绝对路径，这样需要保持构建环境和部署环境的机器目录结构完全一致，泛用性会有一些问题。

考虑将 manifest 中的 item path 更改为相对于扫描 root 目录的相对路径，并且在 artus application 启动时支持以参数形式指定 root 来在不同机器目录结构下复用 manifest

**Comment by hyj1991** [comment]
cc @noahziheng @DuanPengfei

**Comment by hyj1991** [comment]
这里会在启动期带来些微性能开销：`path.resolve`，但是提升了 manifest  的泛用性。

另外此模式在 `app.load(manifest, root)` 和 scanner 中也可以配置为可选，满足完全不能容忍性能损失且自行确保构建环境和部署环境目录完全一致的需求下依旧可以生成和加载全路径形式的 manifest

**Comment by DuanPengfei** [comment]
@hyj1991 LGTM;

**Comment by noahziheng** [comment]
@hyj1991 LGTM，其实应该允许可配，有的场景下这个文件可能是远程 Url

**Comment by noahziheng** [comment]
@hyj1991 可以有
