### ISSUE TITLE
`loader` 的 `is` 方法改成静态

### ISSUE THREAD

**Issue by liuhanqu** [artusjs/core#87]
https://github.com/artusjs/core/blob/master/src/loader/factory.ts#L93

当前 `getLoaderName` 方法获取 `loaderName` 时都需要实例化一次 `loader`，好像没有这个必要性？

**Comment by hyj1991** [comment]
这里是改漏了？之前有个 pr 里想要改成 static 的

**Comment by noahziheng** [comment]
@liuhanqu @hyj1991 Loader 部分有个重构是我在改，还没提交，用于解决 #66 ，其中的 is 会被调整成 static
