### ISSUE TITLE
扫描期间，过滤掉map文件

### ISSUE THREAD

**Issue by wengeezhang** [artusjs/core#97]
core/src/scanner/scan.ts getAllConfig中的代码如下：
```ts
const configFileList = await fs.readdir(path.resolve(root, configDir));
```

如果用户tsc开启了sourceMap为true，此时configFileList会包含map文件。

后续load时会报错

**Comment by JerrysShan** [comment]
https://github.com/artusjs/core/pull/96 这个mr 能解决
