### ISSUE TITLE
plugin声明方式package有点问题

### ISSUE THREAD

**Issue by wengeezhang** [artusjs/core#99]
# 问题
目前一个plugin通过npm包的方式来提供。一个业务引入方式如下：
```ts
export default {
  "application-http": {
    enable: true,
    package: '@gulux/application-http'
  },
};
```
但是现在的artus/core解析plugin文件夹的方式如下，

```ts
if (configItem.package) {
     importPath = require.resolve(configItem.package);
}
```

此时会拿到一个文件，而非文件夹。这样会导致寻找meta.yaml时报错。

# 建议
这个问题之前好像讨论过。目前看，是否可以通过在plugin的package.json中引入一个field，比如：
```ts
{
  pluginDir: './lib'
}
```

然后artus/core就可以知道plugin的目录是什么了。

不过这种方式也很搓！！！

**Comment by wengeezhang** [comment]
## 目前有两个使用限制：
* 用户的package.json可能设置了exports
* 框架开发调试时，可能用的是软链

## 可能的解决方案：
目前看，如果做一个限制，即artus的插件必须支持“@group/pkg/meta.yaml"导出即可。

## 现在还剩下另外一个问题：
本地开发时，是用的软连，上层基础包比如@gulux/application里的代码（即引入的artus/core）是无法通过require.resolve()来解析包的地址的。

**Comment by JerrysShan** [comment]
约定 `package.json` 文件必须导出，然后根据这个文件的路径去接卸是不是也可以

**Comment by JerrysShan** [comment]
#98

**Comment by wengeezhang** [comment]
结论：
# 约定的包的一级导出设置（exports坑位）
* meta.yaml
* package.json
* exception.yaml

# 约定meta.yaml必须在包的一级目录下

# artus/core通过上面的约定，读取到plugin的扫描目录

注: 目前扫描器的实现，会有限读取meta中的configDir，所以这块暂时不用改动。
